{% set name = "pygeoops" %}
{% set version = "0.2.0.post0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 53429bf79127439d7db06a3d7e35de2f2e2917a3ed76d6dc7dd2bc14210f2b48

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - geopandas
    - shapely >1
    - topojson

test:
  imports:
    - pygeoops
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pygeoops/pygeoops
  summary: Library with some less common or extended spatial functions
  description: |
    PyGeoOps provides some less common or extended spatial algorithms and utility functions.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://pygeoops.readthedocs.io
  dev_url: https://github.com/pygeoops/pygeoops

extra:
  recipe-maintainers:
    - theroggy
