{% set name = "pygeoops" %}
{% set version = "0.6.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 062282752fd6c6f1255fb6b31c702379b1466bdb0fd2579b08d21496df35ac82

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    # Standard dependencies
    - geopandas-base >=0.12.1
    - numpy
    - pyproj
    - shapely >1
    - topojson
  run:
    - python >={{ python_min }}
    - geopandas-base >=0.12.1
    - numpy
    - pyproj
    - shapely >1
    - topojson

test:
  requires:
    - python {{ python_min }}
  imports:
    - pygeoops

about:
  home: https://github.com/pygeoops/pygeoops
  summary: 'Library with some less common or extended spatial functions'
  description: |
    PyGeoOps provides some less common or extended spatial algorithms and utility functions.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://pygeoops.readthedocs.io
  dev_url: https://github.com/pygeoops/pygeoops

extra:
  recipe-maintainers:
    - theroggy
